### ISSUE TITLE
Crash when change theme

### ISSUE THREAD

**Issue by DeicPro** [topjohnwu/MagiskManager#115]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ProgressBar.setVisibility(int)' on a null object reference
	at com.topjohnwu.magisk.c.onPostExecute(Unknown Source)
	at android.os.AsyncTask.finish(AsyncTask.java)
	at android.os.AsyncTask.access$600(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.app.ActivityThread.main(ActivityThread.java)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
```

**Comment by linar10** [comment]
It works ok, clean application data

**Comment by DeicPro** [comment]
IDK why this bug if I did clean install... Thanks @linar10.
