### ISSUE TITLE
[BUG] Running SafetyNet check again after already run results in crash on O-Preview (Nexus 6P)

### ISSUE THREAD

**Issue by Maxr1998** [topjohnwu/MagiskManager#196]
Here's the stacktrace, latest Magisk Beta from the official thread (`96f8efc`):
```
06-21 11:45:34.449 19328 19328 D AndroidRuntime: Shutting down VM
06-21 11:45:34.480 19328 19328 E AndroidRuntime: FATAL EXCEPTION: main
06-21 11:45:34.480 19328 19328 E AndroidRuntime: Process: com.topjohnwu.magisk, PID: 19328
06-21 11:45:34.480 19328 19328 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/animation/Animator$AnimatorListener$$CC;
06-21 11:45:34.480 19328 19328 E AndroidRuntime: 	at com.topjohnwu.magisk.MagiskFragment$4.onAnimationStart(Unknown Source:0)
06-21 11:45:34.480 19328 19328 E AndroidRuntime: 	at android.animation.ValueAnimator.notifyStartListeners(ValueAnimator.java:990)
06-21 11:45:34.480 19328 19328 E AndroidRuntime: 	at android.animation.ValueAnimator.startAnimation(ValueAnimator.java:1239)
06-21 11:45:34.480 19328 19328 E AndroidRuntime: 	at android.animation.ValueAnimator.start(ValueAnimator.java:1041)
06-21 11:45:34.480 19328 19328 E AndroidRuntime: 	at android.animation.ValueAnimator.start(ValueAnimator.java:1065)
06-21 11:45:34.480 19328 19328 E AndroidRuntime: 	at com.topjohnwu.magisk.MagiskFragment.aj(Unknown Source:24)
06-21 11:45:34.480 19328 19328 E AndroidRuntime: 	at com.topjohnwu.magisk.MagiskFragment.safetyNet(Unknown Source:28)
06-21 11:45:34.480 19328 19328 E AndroidRuntime: 	at com.topjohnwu.magisk.MagiskFragment_ViewBinding$4.a(Unknown Source:2)
06-21 11:45:34.480 19328 19328 E AndroidRuntime: 	at butterknife.a.a.onClick(Unknown Source:12)
06-21 11:45:34.480 19328 19328 E AndroidRuntime: 	at android.view.View.performClick(View.java:6219)
06-21 11:45:34.480 19328 19328 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:24482)
06-21 11:45:34.480 19328 19328 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:769)
06-21 11:45:34.480 19328 19328 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
06-21 11:45:34.480 19328 19328 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
06-21 11:45:34.480 19328 19328 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
06-21 11:45:34.480 19328 19328 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-21 11:45:34.480 19328 19328 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
06-21 11:45:34.480 19328 19328 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
06-21 11:45:34.480 19328 19328 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.animation.Animator$AnimatorListener$$CC" on path: DexPathList[[zip file "/data/app/com.topjohnwu.magisk-Pq8tVKUEFhSIFtMmysaGOA==/base.apk"],nativeLibraryDirectories=[/data/app/com.topjohnwu.magisk-Pq8tVKUEFhSIFtMmysaGOA==/lib/arm, /data/app/com.topjohnwu.magisk-Pq8tVKUEFhSIFtMmysaGOA==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
06-21 11:45:34.480 19328 19328 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
06-21 11:45:34.480 19328 19328 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
06-21 11:45:34.480 19328 19328 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
06-21 11:45:34.480 19328 19328 E AndroidRuntime: 	... 18 more
06-21 11:45:34.509   776  3119 W ActivityManager:   Force finishing activity com.topjohnwu.magisk/.MainActivity
06-21 11:45:34.524   776   802 I ActivityManager: Showing crash dialog for package com.topjohnwu.magisk u0
```

**Comment by Maxr1998** [comment]
Update: this seems to be an upstream bug with the build-tools, already fixed but not released yet.
https://issuetracker.google.com/issues/62680180

**Comment by topjohnwu** [comment]
Clean project and rebuild should fix the issue
