### ISSUE TITLE
FC when tapping update notification

### ISSUE THREAD

**Issue by terrorist96** [topjohnwu/MagiskManager#217]
@topjohnwu When opening the app (coming from version 13.1/5.0.4) and checking for an update, I get two notifications. One that says there's an update and one that says "tap here to download the update". If I tap the first one, it just reopens the app. If I tap the second one, it will start to download the update file, but the app then crashes immediately. I was able to update by just tapping the install button at the bottom of the app's home page (instead of the notification).
Log:
>java.lang.RuntimeException: Unable to start receiver com.topjohnwu.magisk.receivers.ManagerUpdate: android.content.ReceiverCallNotAllowedException: BroadcastReceiver components are not allowed to register to receive intents
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2732)
at android.app.ActivityThread.-wrap14(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5422)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
Caused by: android.content.ReceiverCallNotAllowedException: BroadcastReceiver components are not allowed to register to receive intents
at android.app.ReceiverRestrictedContext.registerReceiver(ContextImpl.java:96)
at android.app.ReceiverRestrictedContext.registerReceiver(ContextImpl.java:85)
at com.topjohnwu.magisk.utils.g.a(Unknown Source)
at com.topjohnwu.magisk.receivers.ManagerUpdate.onReceive(Unknown Source)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2725)
... 9 more

Reading the changelog for 5.0.5 says:

> - Fix crash when trying to install Magisk Manager update

I'm assuming this is fixed now? Can you confirm? Thanks.

**Comment by topjohnwu** [comment]
Yes, it fixed, thanks :)
