### ISSUE TITLE
[BUG]Magisk 无法在多用户模式下正常运行（Magisk has some bugs in multi-user mode）

### ISSUE THREAD

**Issue by snooby2333** [topjohnwu/MagiskManager#238]
红米Note 4，处理器是联发科Helio X20(mt6797)，系统是MIUI 7.6.10。
(Redmi Note 4,the CPU is mt6797,running in miui 7.6.10.)
在新用户空间下可以正常安装Magisk Manager，但是无法正常运行，会崩溃退出。
(The Magisk Manager will crash when I want to start it in the new userspace.) 
而且，就算在初始用户空间内的Magisk Manager里设置“多用户模式“为“各用户独立”，也无法在新用户空间下正常获取root权限。
Magisk Manager崩溃时的系统日志：
(Log output when Magisk Manager crash:)
java.lang.RuntimeException: Unable to create application com.topjohnwu.magisk.MagiskManager: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4969)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
	at android.app.ActivityThread.handleBindApplication(<Xposed>)
	at android.app.ActivityThread.access$1700(ActivityThread.java:180)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1555)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5793)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
	at com.topjohnwu.magisk.utils.f.<init>(Unknown Source)
	at com.topjohnwu.magisk.utils.f.a(Unknown Source)
	at com.topjohnwu.magisk.MagiskManager.onCreate(Unknown Source)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1018)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4966)
	... 12 more

Magisk的日志：
(Log output of Magisk:)
--------- beginning of main
07-22 12:56:15.415   321   321 I Magisk  : Magisk v13.3(1330) daemon started
07-22 12:56:15.422   321   334 I Magisk  : ** post-fs mode running
--------- beginning of system
--------- beginning of crash
 AppSystemizer
*** Universal SafetyNet Fix > START
+ '[' -d /data/data/com.topjohnwu.magisk/busybox ']'
+ BUSYBOX=/data/data/com.topjohnwu.magisk/busybox/ 
+ RESETPROP='resetprop -v -n' 
+ '[' -f /sbin/magisk ']'
+ RESETPROP='/sbin/magisk resetprop -v -n' 
+ /sbin/magisk resetprop -v -n ro.build.fingerprint Xiaomi/sagit/sagit:7.1.1/NMF26X/V8.2.17.0.NCACNEC:user/release-keys
resetprop: setprop [ro.build.fingerprint]: [Xiaomi/sagit/sagit:7.1.1/NMF26X/V8.2.17.0.NCACNEC:user/release-keys] by modifing prop data structure
+ /sbin/magisk resetprop -v -n ro.bootimage.build.fingerprint Xiaomi/sagit/sagit:7.1.1/NMF26X/V8.2.17.0.NCACNEC:user/release-keys
resetprop: setprop [ro.bootimage.build.fingerprint]: [Xiaomi/sagit/sagit:7.1.1/NMF26X/V8.2.17.0.NCACNEC:user/release-keys] by modifing prop data structure
+ /sbin/magisk resetprop -v -n ro.build.type user
resetprop: setprop [ro.build.type]: [user] by modifing prop data structure
+ /sbin/magisk resetprop -v -n ro.build.tags release-keys
resetprop: setprop [ro.build.tags]: [release-keys] by modifing prop data structure
+ /sbin/magisk resetprop -v -n ro.build.selinux 0
resetprop: New prop [ro.build.selinux]
resetprop: setprop [ro.build.selinux]: [0] by modifing prop data structure
+ /sbin/magisk resetprop -v -n selinux.reload_policy 1
resetprop: New prop [selinux.reload_policy]
resetprop: setprop [selinux.reload_policy]: [1] by modifing prop data structure
+ /sbin/magisk resetprop -v -n persist.magisk.hide 1
resetprop: New prop [persist.magisk.hide]
resetprop: setprop [persist.magisk.hide]: [1] by modifing prop data structure
+ exit
+ background
+ set +x
+ break
+ sleep 5
+ getprop magisk.version
+ '['  '==' 12.0 ']'
+ magisk -v
+ 2>/dev/null 
+ grep '13.0(.*):MAGISK'
+ '['  ']'
+ set +x
*** Universal SafetyNet Fix > END

**Comment by snooby2333** [comment]
My english isn't well,if you can't get the point,plz tell me.Thanks.

**Comment by indianpoptart** [comment]
I have the same issue on a Nexus 6 running LOS 14.1

**Comment by topjohnwu** [comment]
Should be fixed
