### ISSUE TITLE
[BUG] If device does not have any web browser installed, click the Souce code Magisk Manager will be FC

### ISSUE THREAD

**Issue by kaneawk** [topjohnwu/MagiskManager#246]
## Environment
Magisk Manager version: 5.1.1
Android Version: 7.0
Device: Moto z

## Bug description
If device does not have any web browser installed, click About->Souce code Magisk Manager will be FC.

## Error log:

07-30 01:26:28.554   661   661 I SFPerfTracer:      triggers: (rate: 13:720) (compose: 0:1) (post: 0:9) (render: 0:2) (56:14488 frames) (57:15732)
07-30 01:26:28.555   661   661 D SFPerfTracer:        layers: (3:9) (com.android.systemui.ImageWallpaper (0x7a08316800): 0:5099)* (StatusBar (0x7a087da800): 0:6248) (NavigationBar (0x7a08330800): 0:5824) (animation background stackId=0 (0x7a086b7000): 0:2)* (DimLayerController/Stack=0 (0x7a086b8c00): 0:646)* (animation background stackId=1 (0x7a0831f400): 0:32)* (Sprite (0x7a0867e000): 0:6)* (com.topjohnwu.magisk/com.topjohnwu.magisk.MainActivity (0x7a08348c00): 0:114)- (com.topjohnwu.magisk/com.topjohnwu.magisk.AboutActivity (0x7a0622d000): 57:102)
07-30 01:26:28.649  1944  2621 I ActivityManager: START u0 {act=android.intent.action.VIEW dat=https://github.com/...} from uid 10098 on display 0
07-30 01:26:28.649   886  1027 I ThermalEngine: Thermal-Server: Thermal received msg from  override
07-30 01:26:28.649   520  7663 I Thermal-Lib: Thermal-Lib-Client: Client request sent
07-30 01:26:28.650  7552  7552 D AndroidRuntime: Shutting down VM
07-30 01:26:28.651  7552  7552 E AndroidRuntime: FATAL EXCEPTION: main
07-30 01:26:28.651  7552  7552 E AndroidRuntime: Process: com.topjohnwu.magisk, PID: 7552
07-30 01:26:28.651  7552  7552 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://github.com/... }
07-30 01:26:28.651  7552  7552 E AndroidRuntime:        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1899)
07-30 01:26:28.651  7552  7552 E AndroidRuntime:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1589)
07-30 01:26:28.651  7552  7552 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:4239)
07-30 01:26:28.651  7552  7552 E AndroidRuntime:        at android.support.v4.app.e.startActivityForResult(Unknown Source)
07-30 01:26:28.651  7552  7552 E AndroidRuntime:        at android.support.v4.app.h.startActivityForResult(Unknown Source)
07-30 01:26:28.651  7552  7552 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:4198)
07-30 01:26:28.651  7552  7552 E AndroidRuntime:        at android.support.v4.app.h.startActivityForResult(Unknown Source)
07-30 01:26:28.651  7552  7552 E AndroidRuntime:        at android.app.Activity.startActivity(Activity.java:4526)
07-30 01:26:28.651  7552  7552 E AndroidRuntime:        at android.app.Activity.startActivity(Activity.java:4494)
07-30 01:26:28.651  7552  7552 E AndroidRuntime:        at com.topjohnwu.magisk.AboutActivity.c(Unknown Source)
07-30 01:26:28.651  7552  7552 E AndroidRuntime:        at com.topjohnwu.magisk.d.onClick(Unknown Source)
07-30 01:26:28.651  7552  7552 E AndroidRuntime:        at android.view.View.performClick(View.java:5612)
07-30 01:26:28.651  7552  7552 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:22285)
07-30 01:26:28.651  7552  7552 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
07-30 01:26:28.651  7552  7552 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
07-30 01:26:28.651  7552  7552 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
07-30 01:26:28.651  7552  7552 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6154)
07-30 01:26:28.651  7552  7552 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-30 01:26:28.651  7552  7552 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
07-30 01:26:28.651  7552  7552 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
07-30 01:26:28.654  1944  3007 W ActivityManager:   Force finishing activity com.topjohnwu.magisk/.AboutActivity
07-30 01:26:28.706  1944  4709 I OpenGLRenderer: Initialized EGL, version 1.4
07-30 01:26:28.706  1944  4709 D OpenGLRenderer: Swap behavior 1
07-30 01:26:28.839  1944  2365 D MotoSensors: ALS 18
07-30 01:26:29.160  1944  2036 W ActivityManager: Activity pause timeout for ActivityRecord{8918d4a u0 com.topjohnwu.magisk/.AboutActivity t29 f}
07-30 01:26:29.372  4093  4093 I MotoDisplay: Animations disabled: false
07-30 01:26:29.651   886  1027 I ThermalEngine: Thermal-Server: Thermal received msg from  override
07-30 01:26:29.651   520  7665 I Thermal-Lib: Thermal-Lib-Client: Client request sent
07-30 01:26:29.888  1944  2365 D MotoSensors: ALS 26
07-30 01:26:32.425  4093  4093 I MotoDisplay: Animations disabled: false
07-30 01:26:34.205   661   661 I SFPerfTracer:      triggers: (rate: 13:720) (compose: 0:1) (post: 0:9) (render: 0:2) (325:14818 frames) (326:16068)
07-30 01:26:34.205   661   661 D SFPerfTracer:        layers: (5:9) (com.android.systemui.ImageWallpaper (0x7a08316800): 326:5432)* (StatusBar (0x7a087da800): 326:6581) (NavigationBar (0x7a08330800): 326:6157) (animation background stackId=0 (0x7a086b7000): 0:2)* (DimLayerController/Stack=0 (0x7a086b8c00): 10:656) (animation background stackId=1 (0x7a0831f400): 0:32)* (Sprite (0x7a0867e000): 0:8)* (com.topjohnwu.magisk/com.topjohnwu.magisk.AboutActivity (0x7a0622d000): 326:436) (Application Error: com.topjohnwu.magisk (0x7a06265800): 326:331)

**Comment by topjohnwu** [comment]
Not really sure how to fix that....
