### ISSUE TITLE
Crash upon opening

### ISSUE THREAD

**Issue by terrorist96** [topjohnwu/MagiskManager#258]
java.lang.RuntimeException: Unable to create application com.topjohnwu.magisk.MagiskManager: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4715)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
	at android.app.ActivityThread.handleBindApplication(<Xposed>)
	at android.app.ActivityThread.-wrap1(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5422)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
	at com.topjohnwu.magisk.utils.f.<init>(Unknown Source)
	at com.topjohnwu.magisk.utils.f.a(Unknown Source)
	at com.topjohnwu.magisk.MagiskManager.onCreate(Unknown Source)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4712)
	... 12 more

**Comment by terrorist96** [comment]
It doesn't crash anymore after I rebooted my phone.

**Comment by FabianMeul** [comment]
I am having a crash every time I open the app. (Nexus 6P - 7.1.2)

How can I view the crash logs?

**Comment by terrorist96** [comment]
I used an Xposed module called Scoop. Outside that, you could set up a logcat.
