### ISSUE TITLE
Timeout exception (log)

### ISSUE THREAD

**Issue by terrorist96** [topjohnwu/MagiskManager#274]
java.util.concurrent.TimeoutException: android.os.BinderProxy.finalize() timed out after 10 seconds
	at android.os.BinderProxy.destroy(Native Method)
	at android.os.BinderProxy.finalize(Binder.java:547)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:202)
	at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
	at java.lang.Thread.run(Thread.java:818)

**Comment by topjohnwu** [comment]
I need more logs than this
