### ISSUE TITLE
Null Pointer

### ISSUE THREAD

**Issue by indianpoptart** [topjohnwu/MagiskManager#277]
Hey, this happens from time to time, and I usually have to reboot, but sometimes I have to reinstall magisk.

Seems to happen whenever I run root commands in my app
https://github.com/indianpoptart/RadioControl

Let me know if you need more information

``` java
FATAL EXCEPTION: main
                                                   Process: com.topjohnwu.magisk, PID: 22411
                                                   java.lang.RuntimeException: Unable to create application com.topjohnwu.magisk.MagiskManager: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5451)
                                                       at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1564)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
                                                       at com.topjohnwu.magisk.utils.f.<init>(Unknown Source)
                                                       at com.topjohnwu.magisk.utils.f.a(Unknown Source)
                                                       at com.topjohnwu.magisk.MagiskManager.onCreate(Unknown Source)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5448)
                                                       at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1564) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6186) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
 ```

**Comment by guest4711** [comment]
see also #258

**Comment by topjohnwu** [comment]
This shouldn't be an issue now
