### ISSUE TITLE
Magisk Manager Crash

### ISSUE THREAD

**Issue by Scherzengel** [topjohnwu/MagiskManager#84]
Magisk Manager crashes directly after starting it.

Here is a log of the crash. If you need more info or another log please let me know. Thanks in advance.

02-06 13:30:03.753 E/cutils-trace(32281): Error opening trace file: No such file or directory (2)
02-06 13:30:04.595 E/AndroidRuntime(32212): FATAL EXCEPTION: AsyncTask #1
02-06 13:30:04.595 E/AndroidRuntime(32212): Process: com.topjohnwu.magisk, PID: 32212
02-06 13:30:04.595 E/AndroidRuntime(32212): java.lang.RuntimeException: An error occurred while executing doInBackground()
02-06 13:30:04.595 E/AndroidRuntime(32212): 	at android.os.AsyncTask$3.done(AsyncTask.java:325)
02-06 13:30:04.595 E/AndroidRuntime(32212): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
02-06 13:30:04.595 E/AndroidRuntime(32212): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
02-06 13:30:04.595 E/AndroidRuntime(32212): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
02-06 13:30:04.595 E/AndroidRuntime(32212): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
02-06 13:30:04.595 E/AndroidRuntime(32212): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
02-06 13:30:04.595 E/AndroidRuntime(32212): 	at java.lang.Thread.run(Thread.java:761)
02-06 13:30:04.595 E/AndroidRuntime(32212): Caused by: com.google.gson.JsonSyntaxException: Oct 6, 2016 09:33:43
02-06 13:30:04.595 E/AndroidRuntime(32212): 	at com.google.gson.internal.bind.DateTypeAdapter.deserializeToDate(Unknown Source)
02-06 13:30:04.595 E/AndroidRuntime(32212): 	at com.google.gson.internal.bind.DateTypeAdapter.read(Unknown Source)
02-06 13:30:04.595 E/AndroidRuntime(32212): 	at com.google.gson.internal.bind.DateTypeAdapter.read(Unknown Source)
02-06 13:30:04.595 E/AndroidRuntime(32212): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(Unknown Source)
02-06 13:30:04.595 E/AndroidRuntime(32212): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(Unknown Source)
02-06 13:30:04.595 E/AndroidRuntime(32212): 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(Unknown Source)
02-06 13:30:04.595 E/AndroidRuntime(32212): 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(Unknown Source)
02-06 13:30:04.595 E/AndroidRuntime(32212): 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(Unknown Source)
02-06 13:30:04.595 E/AndroidRuntime(32212): 	at com.google.gson.Gson.fromJson(Unknown Source)
02-06 13:30:04.595 E/AndroidRuntime(32212): 	at com.google.gson.Gson.fromJson(Unknown Source)
02-06 13:30:04.595 E/AndroidRuntime(32212): 	at com.google.gson.Gson.fromJson(Unknown Source)
02-06 13:30:04.595 E/AndroidRuntime(32212): 	at com.topjohnwu.magisk.module.ModuleHelper.createRepoMap(Unknown Source)
02-06 13:30:04.595 E/AndroidRuntime(32212): 	at com.topjohnwu.magisk.utils.l.a(Unknown Source)
02-06 13:30:04.595 E/AndroidRuntime(32212): 	at com.topjohnwu.magisk.utils.l.doInBackground(Unknown Source)
02-06 13:30:04.595 E/AndroidRuntime(32212): 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
02-06 13:30:04.595 E/AndroidRuntime(32212): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-06 13:30:04.595 E/AndroidRuntime(32212): 	... 3 more
02-06 13:30:04.595 E/AndroidRuntime(32212): Caused by: java.text.ParseException: Failed to parse date ["Oct 6, 2016 09:33:43']: Invalid number: Oct 
02-06 13:30:04.595 E/AndroidRuntime(32212): 	at com.google.gson.internal.bind.util.ISO8601Utils.parse(Unknown Source)
02-06 13:30:04.595 E/AndroidRuntime(32212): 	... 19 more
02-06 13:30:04.595 E/AndroidRuntime(32212): Caused by: java.lang.NumberFormatException: Invalid number: Oct 
02-06 13:30:04.595 E/AndroidRuntime(32212): 	at com.google.gson.internal.bind.util.ISO8601Utils.parseInt(Unknown Source)
02-06 13:30:04.595 E/AndroidRuntime(32212): 	... 20 more
02-06 13:30:05.048 E/WindowManager(32212): 
02-06 13:30:05.048 E/WindowManager(32212): android.view.WindowLeaked: Activity com.topjohnwu.magisk.MainActivity has leaked window DecorView@f89902e[] that was originally added here
02-06 13:30:05.048 E/WindowManager(32212): 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:418)
02-06 13:30:05.048 E/WindowManager(32212): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
02-06 13:30:05.048 E/WindowManager(32212): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
02-06 13:30:05.048 E/WindowManager(32212): 	at android.app.Dialog.show(Dialog.java:322)
02-06 13:30:05.048 E/WindowManager(32212): 	at com.topjohnwu.magisk.StatusFragment.a(Unknown Source)
02-06 13:30:05.048 E/WindowManager(32212): 	at com.topjohnwu.magisk.StatusFragment.a(Unknown Source)
02-06 13:30:05.048 E/WindowManager(32212): 	at com.topjohnwu.magisk.utils.b.b(Unknown Source)
02-06 13:30:05.048 E/WindowManager(32212): 	at com.topjohnwu.magisk.utils.b.e(Unknown Source)
02-06 13:30:05.048 E/WindowManager(32212): 	at com.topjohnwu.magisk.utils.c.c(Unknown Source)
02-06 13:30:05.048 E/WindowManager(32212): 	at com.topjohnwu.magisk.utils.c.b(Unknown Source)
02-06 13:30:05.048 E/WindowManager(32212): 	at com.topjohnwu.magisk.utils.j.b(Unknown Source)
02-06 13:30:05.048 E/WindowManager(32212): 	at com.topjohnwu.magisk.utils.j.onPostExecute(Unknown Source)
02-06 13:30:05.048 E/WindowManager(32212): 	at android.os.AsyncTask.finish(AsyncTask.java:667)
02-06 13:30:05.048 E/WindowManager(32212): 	at android.os.AsyncTask.-wrap1(AsyncTask.java)
02-06 13:30:05.048 E/WindowManager(32212): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
02-06 13:30:05.048 E/WindowManager(32212): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-06 13:30:05.048 E/WindowManager(32212): 	at android.os.Looper.loop(Looper.java:154)
02-06 13:30:05.048 E/WindowManager(32212): 	at android.app.ActivityThread.main(ActivityThread.java:6126)
02-06 13:30:05.048 E/WindowManager(32212): 	at java.lang.reflect.Method.invoke(Native Method)
02-06 13:30:05.048 E/WindowManager(32212): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
02-06 13:30:05.048 E/WindowManager(32212): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by Scherzengel** [comment]
Ver. 4.1 is working again. Thanks allot.
